blank_issues_enabled: false
contact_links:
  - name: Join Our CNCF Slack Channel kubeflow-platform..
    url: https://www.kubeflow.org/docs/about/community/
    about: Join our CNCF Slack Channel and access our meeting schedule.
  
  