name: Proper Formatting on bash files

on: [push, pull_request]

jobs:
  format_bash_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install ShellCheck
      run: sudo apt install -y shellcheck

    - name: Run ShellCheck
      run: find . -type f -name "*.sh" -exec shellcheck {} +

