name: Appy PSS labels to namespaces
on:
  pull_request:
    paths:
    - tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
    - .github/workflows/*
    - tests/gh-actions/kind-cluster.yaml
    - apps/profiles/upstream/**
    - common/dex/**
    - common/cert-manager/**
    - common/oidc-client/oauth2-proxy/**
    - common/istio*/**
    - tests/gh-actions/install_istio_with_ext_auth.sh
    - tests/gh-actions/install_multitenancy.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install KinD, Create KinD cluster and Install kustomize
      run: ./tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh

    - name: Install kubectl
      run: ./tests/gh-actions/install_kubectl.sh

    - name: Applying Pod Security Standards baseline levels for static namespaces
      run: ./tests/gh-actions/enable_baseline_PSS.sh
