name: Proper Formatting on Python files

on: [push, pull_request]

jobs:
  format_python_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: psf/black@stable
        with:
          src: |
            ./common
            ./example

    