name: Build & Apply Ray manifest in KinD
on:
  pull_request:
    paths:
    - .github/workflows/ray_test.yaml
    - contrib/ray/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Install KinD, Create KinD cluster and Install kustomize
      run: |
        chmod +x tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
        ./tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh

    - name: Build & Apply manifests
      run: |
        cd contrib/ray/
        make test
